channel: stable-4.18
version: 4.18.7
subscriptions:
  #- name: kiali-ossm
  #  namespace: openshift-operators
  #  channel: stable
  #  source: redhat-operators
  #- name: servicemeshoperator
  #  namespace: openshift-operators
  #  channel: stable
  #  source: redhat-operators
  - name: amq-streams
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  #- name: serverless-operator
  #  namespace: openshift-serverless
  #  channel: stable
  #  source: redhat-operators
  - name: gitlab-operator-kubernetes
    namespace: gitlab-system
    channel: stable
    source: certified-operators
rhdh:
  namespace: rhdh-operator
  channel: fast
  startingCSV: rhdh-operator.v1.6.3
  enabled: true
rhbk:
  namespace: rhbk-operator
  channel: stable-v26.2
  startingCSV: rhbk-operator.v26.2.5-opr.1
  enabled: true

acs:
  enabled: false
sealedsecrets:
  enabled: false
gitops:
  enabled: false
knative:
  enabled: false
kafka:
  enabled: false
  dedicatedNode: false
patchoperator:
  enabled: true
gitlab:
  enabled: false