channel: stable-4.18
version: 4.18.7
subscriptions:
  #- name: kiali-ossm
  #  namespace: openshift-operators
  #  channel: stable
  #  source: redhat-operators
  - name: servicemeshoperator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: amq-streams
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  - name: serverless-operator
    namespace: openshift-serverless
    channel: stable
    source: redhat-operators
  #- name: serverless-operator
  #  namespace: openshift-serverless
  #  channel: stable
  #  source: redhat-operators
rhdh:
  namespace: developer-hub
  channel: stable
rhbk:
  namespace: rhbk
  channel: stable-v26.2
  startingCSV: rhbk-operator.v26.2.5-opr.1

acs:
  enabled: false
sealedsecrets:
  enabled: false
gitops:
  enabled: false
knative:
  enabled: true
kafka:
  enabled: true
  dedicatedNode: false