apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-global
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '{{name}}-cluster-config'
    spec:
      destination:
        server: '{{server}}'
      project: default
      source:
        path: clusters
        repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
        targetRevision: master
        helm:
          valueFiles:
            - values-remote.yaml
      syncPolicy:
        automated:
          selfHeal: true