apiVersion: v1
kind: Namespace
metadata:
  name: interconnect
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    skupper.io/type: connection-token-request
  name: token-req
  namespace: interconnect
  