{{- if eq .Values.gitlab.enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-gitlab-writer # A descriptive name for the Role
  namespace: gitlab-system    # <--- Important: This Role is specific to the 'gitlab-system' namespace
rules:
  - apiGroups:
      - "apps.gitlab.com" # The API group for the GitLab custom resource
    resources:
      - "gitlabs"         # The specific resource type (plural form)
      - "gitlabs/status"  # Often needed for status updates by controllers
    verbs:
      - "create"          # The permission that was denied
      - "get"             # Add other common verbs for full management (recommended for deployment tools)
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-gitlab-binding # A descriptive name for the RoleBinding
  namespace: gitlab-system    # <--- Important: This RoleBinding is specific to the 'gitlab-system' namespace
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller # The name of ArgoCD's service account
    namespace: openshift-gitops                        # The namespace where ArgoCD's service account lives
roleRef:
  kind: Role
  name: argocd-gitlab-writer # Refers to the Role created above
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager:
        install: false
        installCRDs: false        
      global:
        hosts:
          domain: gitlab.apps.rosa.pn5b9-qahb9-a25.2nw2.p3.openshiftapps.com
          https: true
          gitlabVersion: "16.7.7"
        ingress:
          enabled: false
        edition: ce
      nginx-ingress:       
        enabled: false
      gitlab-runner:
        install: false                             
    version: '9.2.0'
{{- end }}