{{- if eq .Values.gitlab.enabled true }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.rhbk.channel }}
{{- if $.Values.rhbk.startingCSV }}
  startingCSV: {{ .Values.rhbk.startingCSV }}
{{- end }}
  installPlanApproval: Automatic
  name: gitlab-operator-kubernetes
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
    - gitlab-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-gitlab-writer 
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
rules:
  - apiGroups:
      - "apps.gitlab.com" 
    resources:
      - "gitlabs"         
      - "gitlabs/status"  
    verbs:
      - "create"          
      - "get"             
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-gitlab-binding 
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller 
    namespace: openshift-gitops                        
roleRef:
  kind: Role
  name: argocd-gitlab-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  chart:
    values:
      certmanager:
        install: false
        installCRDs: false        
      global:
        hosts:
          domain: gitlab.apps.rosa.zy23e-kp42c-iym.ktcw.p3.openshiftapps.com
          https: true
          gitlabVersion: "16.7.7"
        ingress:
          enabled: false
        edition: ce
      nginx-ingress:       
        enabled: false
      gitlab-runner:
        install: false                             
    version: '9.2.1'
{{- end }}