{{- if eq .Values.gitlab.enabled true }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.gitlab.channel }}
{{- if $.Values.gitlab.startingCSV }}
  startingCSV: {{ .Values.gitlab.startingCSV }}
{{- end }}
  installPlanApproval: Automatic
  name: gitlab-operator-kubernetes
  source: {{ .Values.gitlab.source | default "certified-operators" }}
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
    - gitlab-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-gitlab-writer
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - "apps.gitlab.com"
    resources:
      - "gitlabs"
      - "gitlabs/status"
    verbs:
      - "create"
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
  - apiGroups: [""] # "" represents the core API group, which ServiceAccounts belong to
    resources: ["serviceaccounts"]
    verbs:
      - "create"
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-gitlab-binding
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-gitlab-writer
  apiGroup: rbac.authorization.k8s.io
---
# New ClusterRole for IngressClass
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-ingressclass-creator
  # No namespace here, as it's cluster-scoped
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
# New ClusterRoleBinding for IngressClass
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-ingressclass-binding-cluster
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: argocd-ingressclass-creator # This must match the ClusterRole name above
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: gitlab-nginx
spec:
  controller: k8s.io/ingress-nginx
---
# ---
# # SCC Definition - THIS MUST BE APPLIED SEPARATELY TO THE CLUSTER!
# Save this as gitlab-nginx-final-scc.yaml (OVERWRITE YOUR EXISTING FILE)
# apiVersion: security.openshift.io/v1
# kind: SecurityContextConstraints
# metadata:
#   name: gitlab-nginx-final-scc
# allowPrivilegeEscalation: false # As per your generated pod
# requiredDropCapabilities:
# - ALL
# allowedCapabilities:
# - NET_BIND_SERVICE # Essential for NGINX
# runAsUser:
#   type: MustRunAs
#   uid: 101 # NGINX's user
# runAsGroup:
#   type: MustRunAs
#   uid: 82 # NGINX's group
# fsGroup:
#   type: RunAsAny
# supplementalGroups:
#   type: RunAsAny
# seLinuxContext:
#   type: RunAsAny
# priority: 100 # HIGH PRIORITY to ensure it's picked over restricted-v2
# users: [] # This list is populated by the ClusterRoleBinding
# volumes:
# - configMap
# - downwardAPI
# - emptyDir
# - persistentVolumeClaim
# - projected
# - secret
# # --- ADD THIS BLOCK ---
# seccompProfiles:
# - runtime/default # Allow the 'RuntimeDefault' seccomp profile
# - unconfined      # Allow 'Unconfined' as a fallback/option
# --- END ADD BLOCK ---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:gitlab-nginx-final-scc'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - gitlab-nginx-final-scc
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-nginx-final-scc-binding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: gitlab-nginx-ingress
    namespace: gitlab-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:gitlab-nginx-final-scc'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-nginx-ingress-leader-elector
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-nginx-ingress-leader-elector-binding
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
subjects:
  - kind: ServiceAccount
    name: gitlab-nginx-ingress 
    namespace: gitlab-system
roleRef:
  kind: Role
  name: gitlab-nginx-ingress-leader-elector
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-nginx-ingress-tcp
  namespace: gitlab-system
data:
  "22": "gitlab-system/gitlab-gitlab-shell:22"
---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  chart:
    values:
      certmanager:
        install: false
        #installCRDs: false
      global:
        hosts:
          domain: gitlab.apps.rosa.zy23e-kp42c-iym.ktcw.p3.openshiftapps.com
          https: true
          gitlabVersion: "18.2.1"
        ingress:
          configureCertmanager: false
          tls:
            secretName: null
        edition: ce
        postgresql:
          primary:
            extendedConfiguration: max_connections = 200
      nginx-ingress:
        enabled: true      
        controller:           
          containerSecurityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE 
              drop:
                - ALL 
            runAsUser: 101       
            runAsGroup: 82       
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false 
            seccompProfile:
              type: "RuntimeDefault"            
      gitlab-runner:
        install: false
    version: '9.2.1'
{{- end }}