{{- if eq .Values.gitlab.enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-gitlab-writer 
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
rules:
  - apiGroups:
      - "apps.gitlab.com" 
    resources:
      - "gitlabs"         
      - "gitlabs/status"  
    verbs:
      - "create"          
      - "get"             
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-gitlab-binding 
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller 
    namespace: openshift-gitops                        
roleRef:
  kind: Role
  name: argocd-gitlab-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  chart:
    values:
      certmanager:
        install: false
        installCRDs: false        
      global:
        hosts:
          domain: gitlab.apps.rosa.pn5b9-qahb9-a25.2nw2.p3.openshiftapps.com
          https: true
          gitlabVersion: "16.7.7"
        ingress:
          enabled: false
        edition: ce
      nginx-ingress:       
        enabled: false
      gitlab-runner:
        install: false                             
    version: '9.2.0'
{{- end }}