{{- if eq .Values.gitops.enabled true }}
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    values:
      certmanager:
        install: false
        installCRDs: false        
      global:
        hosts:
          domain: apps.rosa.pn5b9-qahb9-a25.2nw2.p3.openshiftapps.com
          https: true
          gitlabVersion: "16.7.7"
        ingress:
          enabled: false
        edition: ce
      nginx-ingress:       
        enabled: false
      gitlab-runner:
        install: false                             
    version: '7.4.0'
{{- end }}