apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.rhbk.channel }}
{{- if $.Values.rhbk.startingCSV }}
  startingCSV: {{ .Values.rhbk.startingCSV }}
{{- end }}
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace