apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh-operator
  namespace: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.rhdh.channel }}
{{- if $.Values.rhdh.startingCSV }}
  startingCSV: {{ .Values.rhdh.startingCSV }}
{{- end }}
  installPlanApproval: Automatic
  name: rhdh-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: rhdh-operator
  namespace: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
    - rhdh-operator