apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: sample-spring-kotlin-test
  annotations:
    skupper.io/address: sample-kotlin-spring-microservice
    skupper.io/port: '8080'
    skupper.io/proxy: http
  name: sample-kotlin-spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-kotlin-spring
  template:
    metadata:
      labels:
        app: sample-kotlin-spring
    spec:
      containers:
        - image: 'quay.io/pminkows/sample-kotlin-spring:1.4.39'
          name: sample-kotlin-spring
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: sample-spring-kotlin-test
  name: sample-kotlin-spring-service
spec:
  ports:
    - name: http-port
      port: 8080
  selector:
    app: sample-kotlin-spring
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sample-kotlin-spring
    app.kubernetes.io/component: sample-kotlin-spring
    app.kubernetes.io/instance: sample-spring-kotlin-test
  name: sample-kotlin-spring-route
spec:
  port:
    targetPort: http-port
  to:
    kind: Service
    name: sample-kotlin-spring-service
    weight: 100
  wildcardPolicy: None