apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable-1.8
  installPlanApproval: Automatic
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
kind: Namespace
apiVersion: v1
metadata:
  name: interconnect
  labels:
    openshift.io/cluster-monitoring: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: skupper-site
#---
#apiVersion: v1
#data:
#  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMVENDQWhXZ0F3SUJBZ0lSQUlIdGNqMklWYmdnQjJJN2JhenRaSjR3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGMydDFjSEJsY2kxemFYUmxMV05oTUI0WERUSXpNVEl4TVRJeE1EUXhNRm9YRFRJNApNVEl3T1RJeE1EUXhNRm93R2pFWU1CWUdBMVVFQXhNUGMydDFjSEJsY2kxemFYUmxMV05oTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc29rSDNOT2Z2VkNZYmdjc2VobXNkYnNNbHNCa2tUWTEKSUpubnRRYlEyMzlzMytRTDdzZ3BjL0VxVHV3M3pxdjlwc0Npb3RFajd6cmV6Qmk0REo0UThlcFIySXJsMzh4TwpRSEhFYmdWMXczTXhSVWJKVVBaUjIrSmhEV21Hbll2VTZFTlFkSmVUcHNTWkZEQmdLM1d2SmxIbG9iQmpFYlBPCjcreWcyRzFmWjNmS0JDZEhlYm1hS05yRFFmQkRYUFNLTHdkeFU4Sk9GV3pTV1ZwMnp3YlhmV2NnTHNmM3BVeHQKMGRZY3RqWXBqSk43b05RTldBalpnUlRobEJxbjNlOUZKeVpDRXk2c0htaHN0aUc1VnlMNTRXZzRWNk95ZTFIUwpadXdxYTdGVnY2cURKWnoycUFYem9GdW9vOXRRaG01aDA1bEVkME5QclhpRnhubURjMlc0YVFJREFRQUJvMjR3CmJEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkxqcGREQ3ExaWk1N0NDWnN3TWhvR0VUUkxCNwpNQXNHQTFVZEVRUUVNQUtDQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQU5GbC9NeFF4NXQycktoSHcrUndECnZBVkp5YWhyZ212MnRRNkw0L3RJQUd4V3Y2VXFyOFhmeUVteUdudWFicEtndWFvekdIeXlxRlk4TDJrRHViZUQKWHE4VU9namphQlhONkJ5bFJyaDZOTFRSYjBJanVRWmt0clhLOXZpK09HUWhBT2RCKzQxalFkQnRzMmpqM1VSZApsTjU4bUV4Y3lNemdWL0NzcEJ0WThQZjVoeDVUK0tLdzJDU0Q4azRSaEhxbzFpcXB5T1JwbnJ2L05sd1drQWgvCndoaFQvMEJsZ3dnb2VqTS91bHdZRzdQbWZQbVZ5OGcvellRTmp6eXNMQjlqdkdTcmU0bmh1ZlZ5UjM0ZG0vN3cKTjVtQkxXT1c1QkxXaldZaitOWVkwejZndTlOM0xHT2c3Q2VRWmVIcUExdUJQMVBvODFFT0ZFSjYvNHFtcU9vQwpWUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#  password: MVg2OFJJYmVidWQ2ZWdzcE9QWENNMURI
#kind: Secret
#metadata:
#  annotations:
#    skupper.io/site-version: 1.8.3-rh-1
#  creationTimestamp: null
#  labels:
#    skupper.io/type: token-claim
#  name: token-req
---
kind: Secret
apiVersion: v1
metadata:
  name: token-req
  namespace: interconnect
  labels:
    app.kubernetes.io/instance: cluster-pool-config
    skupper.io/type: connection-token
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    edge-host: skupper-edge-interconnect.apps.xkecxkru.eastus.aroapp.io
    edge-port: '443'
    inter-router-host: skupper-inter-router-interconnect.apps.xkecxkru.eastus.aroapp.io
    inter-router-port: '443'
    skupper.io/generated-by: 1e4bfbef-7d78-4490-8914-4031f6bbde9a
    skupper.io/site-version: 1.8.3-rh-1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMVENDQWhXZ0F3SUJBZ0lSQU9jU2xtZVFaQVdNeHJVWDZtdSsyQkF3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGMydDFjSEJsY2kxemFYUmxMV05oTUI0WERUSTFNRE13TlRBNE1EZ3hNRm9YRFRNdwpNRE13TkRBNE1EZ3hNRm93R2pFWU1CWUdBMVVFQXhNUGMydDFjSEJsY2kxemFYUmxMV05oTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeGRGeTl0d3Rkam1vYVFXbERVQm5nU3U1c0tWRElVVkIKMFRWaTRrOVZSVFdkSTdQN1ZrWHJOeXBCREFGdG1TYmt3WWYrdXNnbEJ6eTkwNlJhRFMrSjA4Vm9oTmUwQmpFcQplRnBRMDN2a3k3cHlBTkxQRG9lOEp1ZXI3Sk1DNDQxYmlWaDZXUUlyN25xYTNZUUEzd043eTZtQ1gyRHIvR2FRCkVDa0JyUUxjOERRc1FnNFlxYWNBZXJyRXVWNVlIdzNrbDM2YzhMT2FtTXZSRVdnaXp3dzd3QkNEbTJsRWNTT24KNGNoTnlNbEQ5MFFnTmxLbENCa3RvY3NEVGxVREcxZnViQ3RXdXVXcGtlY0ZIekJ3MnhJTDc1ZXNTTGRZNDRGaQpGUEpnZlM0VDJYTFpKZzZIdVZsUC9TNzdBaGNsMFpDYktDMldyTmdnUXhzN0pmbjhoK0J6SndJREFRQUJvMjR3CmJEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkt4K1cyN1dzNGVRT3BxdkFxNjFEZG55TElrWgpNQXNHQTFVZEVRUUVNQUtDQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVRJS0ZFWGlIa3ZXVzJCTXNJQ3JOClBVNEZBK2d6c0s5ODIrc3BpMHlhSHlRbU96UmR4Q2x4OHh2bHZRcjdzczN4d2FIVVNINHpnSW5qTFVBSHd0dS8Kdi95NElXZUVNdDVEVThycHlxQXhUOG5WcjBNQlVySVB0UUtsWlpBRjhDSXByUklDcllTQjg0SmVtYW8ySUlUbApwTXArWWNaODJtUFlxWHUyZHJTLzZrWHZFaUZkZzdyNWMrRzZ0U0YwRERGd1J5d3ZGaEFjdDhnOE1GUFBmbEs0ClBZSWlRMWh4RG4wQmhaNUVvY0Z1QVlmcnNkRzdtZjRrQ1phMWdRNHJiVUh4Y3poQlBubVh5eEsvTUtqa1hqbkkKUzBiWGZZWmxhN1NnOVEvUE5iandpS3hjWHlxcTR0VWJxb1hxWmFKRFprWjNDakxuSnI0REdMbUxlK1BSNzFnZwp3QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKakNDQWc2Z0F3SUJBZ0lSQUpsR29MUC9BTHFWOTBKOG1WZ0JaNk13RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGMydDFjSEJsY2kxemFYUmxMV05oTUI0WERUSTFNRE13TlRBNE1qWXpOMW9YRFRNdwpNRE13TkRBNE1qWXpOMW93RkRFU01CQUdBMVVFQXhNSmRHOXJaVzR0Y21WeE1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW0yNGF1WEs5RlBYM3JCOEhxUk9DNUp3L0VCNXhJcGR0bU5lOGZNTkMKb241VDFLZHA3ZEx0dlNDL0JKQ0Mxekd6aFpsVnlZTnZ1bTczNllwVWJIUEcwdXAxTlR2N2dtQk1oN0w2clJ2MApxSko3bWhOeWMzK29yaGpCVXRoN2pzSFBZVkQ2bFVKK3pHNEQ4NUNEa0hMQ1U1OUU0Y1RobEpCenEzbW5zb2dsCkdIUmtCNEY1WmIwS2FnN1B6WDJma1ZwdjBjWWptcmRSZ05qclpubGxoMDFSdWx3VW11czQ4N0tHcjdkSzVva3gKRklXTG5OV29tNnA1WUswTjcwNU1yaWxENUZka1FaVGlMOEhua3JkMnM1RGlOLyt1aTVGbmJqTkY0ZnVGVG5GagpNelN2QnlUUjdLWXg4Zm91ZDNIbm93TkRSSEpOcFFwekRZeFpOWXYybkhBZE1RSURBUUFCbzIwd2F6QU9CZ05WCkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWQKRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVXJINWJidGF6aDVBNm1xOENyclVOMmZJc2lSa3dDd1lEVlIwUgpCQVF3QW9JQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjh0RUxKVkd3ZDArS1NCSXYrS2pFOWNySWVtbDVuCmZMbmpaaWtCTVd4NkVWVXU4Sk43Q2RoQy9YWExmc0pock5HOFFLTUdycFBETWtQZUNGZ2g3eDBBMG5Sb1ZnTTUKWTlpSFB1T0xCeVkzZmFiWXJFNWhqcVc4K3JwUHVpdE55b01nM2ZoeUR4L2FhYmZoczNFNHVhWG4reE90ZVpGZApMWTNmemIyUmw1OVh5QlBiUFNvMmlhdysrT2lWRU1zQXNtaGpWVWZkMmpwR3lQS2xrTnJpQ1MzOXhORmtNLzZpCmU2Rys3a0VuNUJPcGlTR3R6dGl1S2pTalpoeGx3Q3NtbUY2RnA5OUg5RkFUeWJwcS9FWklsS3VPbGNmNjV4a0MKcm1SdVpCSmM1TStDK1RCZ1hHTGlwcnQweldRbjczd0FUQmFqVE9PWVM0cDJ1NkhsZXNvMW9hc3AKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbTI0YXVYSzlGUFgzckI4SHFST0M1SncvRUI1eElwZHRtTmU4Zk1OQ29uNVQxS2RwCjdkTHR2U0MvQkpDQzF6R3poWmxWeVlOdnVtNzM2WXBVYkhQRzB1cDFOVHY3Z21CTWg3TDZyUnYwcUpKN21oTnkKYzMrb3JoakJVdGg3anNIUFlWRDZsVUorekc0RDg1Q0RrSExDVTU5RTRjVGhsSkJ6cTNtbnNvZ2xHSFJrQjRGNQpaYjBLYWc3UHpYMmZrVnB2MGNZam1yZFJnTmpyWm5sbGgwMVJ1bHdVbXVzNDg3S0dyN2RLNW9reEZJV0xuTldvCm02cDVZSzBONzA1TXJpbEQ1RmRrUVpUaUw4SG5rcmQyczVEaU4vK3VpNUZuYmpORjRmdUZUbkZqTXpTdkJ5VFIKN0tZeDhmb3VkM0hub3dORFJISk5wUXB6RFl4Wk5ZdjJuSEFkTVFJREFRQUJBb0lCQUR5QUlUcnFaSnRTR3ZRTwpxQWF5SjVNaEZwTUpwblFXaVh5akRTVnJRL2JJUVkxWEZTNlRtaUt5S21oMmI5ZWY2d2NuNW5Lb0RNZC9CbFVMCm1VMFZ5K0N4anFvSURTQjBwNVZ5bjR6ZWd0OVRGWFdsK0RqcENobXFYU1lJU2lBSlpOVzJsYk9meklkNmsyTXQKYjJpOG90TzEvVFA4Vk9wbFNBRUpPN09NdHhQTEx2eG00STlOUzhhejY3NVR6Q2hWMzNLYW94dDhjVjdXd093aQpiT2dXUkdXV1dUTksvbG5xMXpsSnpWbG9QaTgrTHFUSitkc1Rhd093aWVFMFJJTjQwd2x2ZkxOS1lUOFQ1aHEvClZkeGtkVFNVUGs2K1hQRTVSUlhNZWFydjMyZ2NJQVFpRGNoQkhSNXFlc0x5ZEVhWnhSNHdsY3RrS3VaRnhuVGsKa0s4aCtZRUNnWUVBd1FTZXdRckFVZUhlZkt0MytNS1IzU012d0kwV0V0L3YwUzlHSXAvaHpQWndMSU5tQ0Z6awpOYVo3NHExMVdiV0VJVy9FUko3cFJSODlrbDgxRHhvWFU4bDNtWmtWa1JOSFNQOGovdVBTQnM1b251ZXo4NXp5CjhhUXE3V0N5MmtJVWo4djlkNSt0WlEyVSs5STU3WlRKTmRheC9nZGdMdDdxMzhBRWF1L21DL2tDZ1lFQXppV20KTXArY0lXYVMyTDE1SWZxODJwd3VrSmVVVDRQZUFYclRFcUVQbHpFSnBLMnZyc2liN1pDb2JJdksyVWh4U2dpSQpoZUE5NGF5WXdJY2xTU1JEZkswMEVRbXdMdXFjdWo5T0xhZE0xeHRoY1pnM3B4VHRWWTR1aDIvRUYwMTBhc1lwClpwblFKTWt2QS95eHJDR040OWZKZHB6N3EydXkza2x4dTYrUU9Qa0NnWUFucEY5R25vS3BUbzUzWkhBYmN6cXEKQkZRR1kvT29wTDJJWlFFdWswKzQzTlJsRUFlZ3FCTm13VzZvTzUvaWNObFdWTEltdGN5TEdjTjNrSDVCUDhhUwp1c29KamR0VUZIV0xsSHM4R21aRVo1Z3RLc0ZXdzJGU0o3bDVUMmJzVks0TWFvVUFVSmM0TGZYdlVsbjdaWmQ5CnF6NmJRY0NMWDlVMVp5YUJJQXhMWVFLQmdRQ1MzcmYrTVVFbmV0RDhvbUYvR0FrZEoxRDFxMGo3TGRRcDhid1gKOWJBSjQrSWU5YS9KTXh3RXNaK05WanQ3ZXVWYi9hQm00VkMxVENhNFpKRG4vM0lsamJFZXdteEh3TmRReW5HRQpqVUZ0c0JCSXdrNUVOK0N2cDlEMnBXWnJ3NzlCbzFVenlEcEhPeDdJRkd6eFdpYWhRY2hEUGEwQWdJYTdZRkFyCmkvV1E0UUtCZ0MxMFZLR3hEbDlsTFRzOWZINi84YS9hM0NPSW5jYlZ1NjhnYSswZXNuQ2crV2ExU1ZqN3RyYzIKNDdQbHlJOEIwQ2RNbXdydDhkOElDbEJIWmVZU1hQQVZnaCs3RjhuZmg0ZFZaZFZ1QWhJSEFKdUliOFI2WlBlUQpXbWg2akNQRFJTZUlKTTRoTTdFNUdVaUttNHZHbk80YTJNcjdFYXRsRzVNZFl5SXZ2TXNQCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
type: Opaque
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: prometheus-operator
  name: sample-kotlin-spring
  namespace: interconnect
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /actuator/prometheus
      targetPort: 8080
  selector:
    matchLabels:
      app: sample-kotlin-spring
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interconnect-read
  namespace: interconnect
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
      - services
      - pods
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interconnect-prometheus-k8s-read-binding
  namespace: interconnect
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: interconnect-read