apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-1
spec:
  data:
    - remoteRef:
        key: my-app/secret-password
      secretKey: secret-password
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: conjur
  target:
    creationPolicy: Owner
    name: my-secret